import Navbar from '@/src/components/navbar';
import './global.css';
import { getSession } from '../lib/session';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  return (
    <html lang="en">
      <body>
        {session && <Navbar />}
        {children}
      </body>
    </html>
  );
}
